#!/bin/sh
if mountpoint -q /target; then
	echo "Installing gressgraph to /target"
	cp /src/gressgraph /target
else
	echo "/target is not a mountpoint."
	echo "You can either:"
	echo "- re-run this container with -v /usr/local/bin:/target"
	echo "- extract the gressgraph binary (e.g. cat /src/gressgraph)"
  exit 1
fi
